"""Read-only production interaction smoke test; no messages or CMS writes."""
import json
import re
import sys
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

label = sys.argv[1] if len(sys.argv) > 1 else 'after'
out = Path('.qa/performance')
out.mkdir(parents=True, exist_ok=True)
base = 'http://127.0.0.1:3000'
result = {'checks': [], 'errors': [], 'consoleErrors': [], 'failedResponses': []}

def check(name):
    result['checks'].append(name)
    print(name, flush=True)

with sync_playwright() as p:
    browser = p.chromium.launch(channel='msedge', headless=True)
    context = browser.new_context(viewport={'width':1440,'height':900})
    page = context.new_page()
    page.on('pageerror', lambda e: result['errors'].append(str(e)))
    page.on('console', lambda m: result['consoleErrors'].append(m.text) if m.type == 'error' else None)
    page.on('response', lambda r: result['failedResponses'].append({'url':r.url,'status':r.status}) if r.status >= 400 else None)
    page.goto(base, wait_until='networkidle')
    expect(page.locator('.research-hero')).to_be_visible()
    check('Homepage renders real content')
    page.locator('[data-xray-hero] canvas').click()
    expect(page.locator('[data-xray-hero]')).to_have_attribute('data-zoomed', 'true')
    page.locator('[data-xray-hero] canvas').press('Enter')
    expect(page.locator('[data-xray-hero]')).to_have_attribute('data-zoomed', 'false')
    check('Hero anatomy zoom and keyboard response')
    for current, following in [('Cells','Liquid'),('Liquid','Ambient'),('Ambient','Cells')]:
        page.get_by_role('button', name=f'Open {current} settings', exact=True).click()
        expect(page.get_by_role('dialog')).to_be_visible()
        slider = page.get_by_role('slider').first
        slider.focus()
        slider.press('ArrowRight')
        page.get_by_role('button', name='Reset to defaults', exact=True).click()
        page.keyboard.press('Escape')
        expect(page.get_by_role('dialog')).to_have_count(0)
        page.get_by_role('button', name=re.compile(f'^Environment: {current}')).click()
        expect(page.get_by_role('button', name=f'Open {following} settings', exact=True)).to_be_visible()
        if following == 'Liquid':
            page.locator('.liquid-canvas').wait_for()
            page.wait_for_load_state('networkidle')
            expect(page.locator('.vanta-cells-host canvas')).to_have_count(0)
        elif following == 'Ambient':
            expect(page.locator('.liquid-canvas')).to_have_count(0)
            expect(page.locator('.vanta-cells-host canvas')).to_have_count(0)
        check(f'{current} settings, reset, Escape and switch to {following}')
    for name, route in [('RESEARCH','research'),('PAPERS','publications'),('THESES','thesis'),('PATENTS','patents'),('TIMELINE','timeline'),('NOTES','blog'),('ABOUT','about'),('CONTACT','contact'),('SEARCH','search')]:
        page.get_by_role('link', name=name, exact=True).click()
        page.wait_for_url(f'**/{route}')
        expect(page.locator('h1')).to_be_visible()
        expect(page.get_by_role('button', name='Try Again', exact=True)).to_have_count(0)
        check('Internal navigation: '+route)
    page.goto(base+'/research', wait_until='networkidle')
    page.get_by_role('button',name='Next project',exact=True).click()
    page.get_by_role('button',name='Previous project',exact=True).click()
    check('Research carousel buttons')
    detail = page.locator('a[href^="/research/"]').first
    detail.click()
    expect(page.locator('h1')).to_be_visible()
    expect(page.get_by_role('button', name='Try Again', exact=True)).to_have_count(0)
    check('Research detail content')
    page.goto(base+'/lab', wait_until='networkidle')
    enter = page.get_by_role('button', name=re.compile('^Enter the laboratory'))
    expect(enter).to_be_visible()
    enter.click()
    page.locator('.lab-stage canvas').wait_for(timeout=60000)
    expect(page.locator('.lab-render-status')).to_have_count(0, timeout=60000)
    page.screenshot(path=str(out/f'{label}-lab.png'))
    check('Lab enters 3D and renders scene')
    for name in ['Rotate device view left','Rotate device view right','Zoom in','Zoom out']:
        page.get_by_role('button',name=name,exact=True).click()
    page.get_by_role('button',name='Pause motion',exact=True).click()
    page.get_by_role('button',name='Resume motion',exact=True).click()
    page.get_by_label('3D quality',exact=True).select_option('high')
    page.get_by_label('3D quality',exact=True).select_option('medium')
    check('Lab camera, pause/resume and quality controls')
    page.get_by_role('button',name='Start guided tour',exact=True).click()
    page.get_by_role('button',name=re.compile('Next station')).click()
    page.get_by_role('button',name=re.compile('Previous station')).click()
    page.get_by_role('button',name='End guided tour',exact=True).click()
    check('Lab guided tour and station buttons')
    page.get_by_role('button',name='Inspect Microscope in 3D',exact=True).click()
    expect(page.get_by_role('complementary',name='Selected research record')).to_be_visible()
    page.get_by_role('button',name='Close research panel',exact=True).click()
    page.get_by_role('button',name='2D view',exact=True).click()
    expect(page.locator('.lab-stage canvas')).to_have_count(0)
    check('Lab device popup closes and 2D view releases canvas')
    context.close()
    mobile = browser.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True,device_scale_factor=1)
    page = mobile.new_page()
    page.on('pageerror', lambda e: result['errors'].append(str(e)))
    page.goto(base, wait_until='networkidle')
    expect(page.locator('.research-hero')).to_be_visible()
    page.screenshot(path=str(out/f'{label}-mobile.png'))
    page.get_by_role('button',name='Open navigation',exact=True).click()
    expect(page.locator('#mobile-navigation')).to_be_visible()
    page.screenshot(path=str(out/f'{label}-mobile-menu.png'))
    page.locator('#mobile-navigation').get_by_role('link',name=re.compile('RESEARCH')).click()
    page.wait_for_url('**/research')
    expect(page.locator('#mobile-navigation')).to_have_count(0)
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    check('Mobile homepage, menu, navigation and no horizontal overflow')
    page.goto(base+'/lab', wait_until='networkidle')
    page.get_by_role('button',name=re.compile('^Enter the laboratory')).click()
    page.locator('.lab-stage canvas').wait_for(timeout=60000)
    expect(page.locator('.lab-render-status')).to_have_count(0,timeout=60000)
    page.screenshot(path=str(out/f'{label}-mobile-lab.png'))
    page.get_by_role('button',name='2D view',exact=True).click()
    expect(page.locator('.lab-stage canvas')).to_have_count(0)
    check('Mobile Lab enters 3D and returns to 2D')
    mobile.close()
    browser.close()
(out/f'{label}-verification.json').write_text(json.dumps(result,indent=2))
assert not result['errors'], result['errors']
print(json.dumps(result,indent=2),flush=True)
